# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Myblog', '0002_auto_20170817_2051'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='url',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='url',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
