# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 17:48
from __future__ import unicode_literals

import Myblog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myblog', '0003_auto_20170819_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=220, validators=[Myblog.validators.validate_url, Myblog.validators.validate_dot_com]),
        ),
    ]
